server:
  port: 28006
spring:
  application:
    name: pz-crowd-order
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:28001/eureka
